server:
  port: 8081

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/logdb}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:alterego}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect